apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: keycloak-jwt
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
    - issuer: "http://keycloak.localhost:8080/realms/poc"
      jwksUri: "http://keycloak.iam.svc.cluster.local:8080/realms/poc/protocol/openid-connect/certs"
      forwardOriginalToken: true
    - issuer: "http://keycloak.localhost:8080/realms/master"
      jwksUri: "http://keycloak.iam.svc.cluster.local:8080/realms/master/protocol/openid-connect/certs"
      forwardOriginalToken: true      
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: demo-strict-mtls
  namespace: demo
spec:
  mtls:
    mode: STRICT
