apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: keycloak-jwt
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
    - issuer: "http://keycloak.localhost:8080/realms/poc"
      jwksUri: "http://keycloak.iam.svc.cluster.local:8080/realms/poc/protocol/openid-connect/certs"
      forwardOriginalToken: true
    - issuer: "http://keycloak.localhost:8080/realms/master"
      jwksUri: "http://keycloak.iam.svc.cluster.local:8080/realms/master/protocol/openid-connect/certs"
      forwardOriginalToken: true      
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: spring-workload-authorization
  namespace: demo
spec:
  selector:
    matchLabels:
      app: spring-app

  action: ALLOW

  rules:
    # Service A -> Spring Boot
    - from:
        - source:
            principals:
              - cluster.local/ns/service-a/sa/service-a
      to:
        - operation:
            methods:
              - GET
            paths:
              - /api/internal

    # Istio Ingress Gateway -> Spring Boot
    - from:
        - source:
            principals:
              - cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account
      to:
        - operation:
            paths:
              - /api/public
              - /api/user
              - /api/whoami
              - /api/headers
              - /api/admin
              - /actuator/health

    # OAuth2-Proxy -> Spring Boot
    - from:
        - source:
            principals:
              - cluster.local/ns/iam/sa/oauth2-proxy
      to:
        - operation:
            methods:
              - GET
            paths:
              - /
              - /api/public
              - /api/user
              - /api/whoami
              - /api/headers         
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: demo-strict-mtls
  namespace: demo
spec:
  mtls:
    mode: STRICT
